### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#172]
What should be included in the new release **v2.0.0**.

New features:
- [x] New check: Trailing Whitespace (#150)
- [x] New check: Newline at the end (#152)
- [x] New check: Extra blank line (#167)
- [x] New check: Quote character (#171)
- [x] Ability to skip some checks (#168)
- [x] Add an argument to show available checks (#199)

Improvements:
- [x] Check files not from the current directory (#179)

Refactoring:
- [x] DuplicatedKeyChecker: Replace `String` with `&'a str` (#181)
- [x] EndingBlankLineChecker: Replace `&'static str` with `&'a str` (#185)
- [x] ExtraBlankLineChecker: Replace `&'static str` with `&'a str` (#186)
- [x] IncorrectDelimiterChecker: Replace `&'static str` with `&'a str` (#187)
- [x] KeyWithoutValueChecker: Replace `String` with `&'a str` (#176)
- [x] LeadingCharacterChecker: Replace `&'static str` with `&'a str` (#188)
- [x] QuoteCharacterChecker: Replace `&'static str` with `&'a str` (#189)
- [x] LowercaseKeyChecker: Replace `String` with `&'a str` (#182)
- [x] SpaceCharacterChecker: Replace `String` with `&'a str` (#183)
- [x] UnorderedKeyChecker: Replace `String` with `&'a str` (#184)
- [x] EndingBlankLineChecker: refactor last line check logic (#204)

What do you think?

**Comment by mstruebing** [comment]
Isn't that a case for v2?
I mean - I'm always unsure when thinking about versioning, but imagine someone who is using this tool in CI and updates and it turns red because there is some trailing white space or a missing newline.

To be clear: I don't want to say: fuck it we need to release v2.0 - I'm just unsure if it is the correct way to increase the feature version for this set of new additions.

**Comment by ypann** [comment]
You could disable new checks by default, and provide a cli arg to enable them on demand.
Later you may change defaults on a v2.
That way you wont crash current users and still be able to add things and change defaults.

**Comment by mgrachev** [comment]
> Isn't that a case for v2?
> I mean - I'm always unsure when thinking about versioning, but imagine someone who is using this tool in CI and updates and it turns red because there is some trailing white space or a missing newline.

I don't like the idea of increasing the major version every time we add a new check.

> To be clear: I don't want to say: fuck it we need to release v2.0 - I'm just unsure if it is the correct way to increase the feature version for this set of new additions.

But I like the idea of adding more features to this release and making it v2.0.0 😃 
What do you think about it?

**Comment by mgrachev** [comment]
> my 2 cents: You could disable new checks by default, and provide a cli arg to enable them on demand.
> Later you may change defaults on a v2.
> That way you wont crash current users and still be able to add things and change defaults.

Thank you for your advice, but releasing v2.0.0 is easier than doing what you said.

**Comment by mgrachev** [comment]
We did it! 🎉
https://github.com/dotenv-linter/dotenv-linter/releases/tag/v2.0.0
