### ISSUE TITLE
Release v2.1.0

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#217]
What should be included in the new release v2.1.0.

Features:
- [x] Windows support (#211, #213, #216)
- [x] Recursive search for `.env` files (#223)

Improvements:
- [x] Optimize integration tests (#218)
- [x] Consider blank lines in UnorderedKey check (#221)

infrastructure:
- [x] Provide more short way to install dotenv-linter (#220)

---

What do you think should be included in the new release?

/cc @dotenv-linter/core

**Comment by DDtKey** [comment]
It seems to me that it would be nice to do #112 as well, and it is possible to release a version as _"infrastructure improvements"_.  
Perhaps the minor version can be quite lightweight, in addition, it unlocks the Scoop bucket and installer.
