### ISSUE TITLE
Release v2.2.0

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#238]
What should be included in the new release v2.2.0.

Features:
- [x] Flag to fix lint errors (#225)
  - [x] Add fixer: LowercaseKeyFixer (#228)
  - [x] Add fixer: KeyWithoutValueFixer (#247)
  - [x] Add fixer: SpaceCharacterFixer (#250)
  - [x] Add fixer: DuplicatedKeyFixer (#243)
  - [x] Add fixer: EndingBlankLineFixer (#244)
  - [x] Add fixer: ExtraBlankLineFixer (#245)
  - [x] Add fixer: IncorrectDelimiterFixer (#246)
  - [x] Add fixer: LeadingCharacterFixer (#248)
  - [x] Add fixer: QuoteCharacterFixer (#249)
  - [x] Add fixer: TrailingWhitespaceFixer (#251)
  - [x] Add fixer: UnorderedKeyFixer (#252)
  - [x] Backup files before fixing (#272)
- [x] Control comments (#237)
- [x] Add total problems to output and `--quiet` argument (#242)
- [x] Group lines by control comments (#281)
- [x] Write an integration test for all fixers (#294)

Improvements:
- [x] Character case in keys (DuplicatedKeyChecker) (#205)
- [x] Update logic for IncorrectDelimiterChecker (#267)

Infrastructure:
- [x] Update actions/cache to v2 (#231)

[action-dotenv-linter](https://github.com/dotenv-linter/action-dotenv-linter):
- [ ] Add `--quiet` flag (https://github.com/dotenv-linter/action-dotenv-linter/pull/14)

---

What do you think should be included in the new release?

/cc @dotenv-linter/core

**Comment by DDtKey** [comment]
What do you think about backup files before fixing? This approach using a lot of linters.

But, maybe it is a good issue for the next release (2.3.0?)

**Comment by mstruebing** [comment]
> What do you think about backup files before fixing? This approach using a lot of linters.

I think for this tool this should be somehow mandatory - `.env` files are typically not versioned with a version control system like git. So if the tool would mess up something your `.env` would be lost and it can lead to a lot of work to recreate all values.

**Comment by mgrachev** [comment]
> What do you think about backup files before fixing? This approach using a lot of linters.
> 
> But, maybe it is a good issue for the next release (2.3.0?)

Good catch! I've forgotten about this feature. This feature should be in this release.

**Comment by baile320** [comment]
I saw there wasn't an issue filed for "Backup files before fixing" - does anything about this feature need to be discussed? Or is the requirement to just to append "_(timestamp)" to the filename (.env -> .env_20200817T09:58:32)? Is there a preference on the timestamp format?

I'd gladly submit a PR for this feature if someone is willing to clarify the requirements! 👍

**Comment by mgrachev** [comment]
> I saw there wasn't an issue filed for "Backup files before fixing" - does anything about this feature need to be discussed? Or is the requirement to just to append "_(timestamp)" to the filename (.env -> .env_20200817T09:58:32)? Is there a preference on the timestamp format?
> 
> I'd gladly submit a PR for this feature if someone is willing to clarify the requirements! 👍

I like that proposal 👍

**Comment by baile320** [comment]
I added a draft PR #272 addressing that, and there are some comments/questions that I have in there before it gets reviewed & merged

**Comment by mgrachev** [comment]
All tasks have been done, so we are ready to release v2.2.0 🎉
I am going to open PR of the release today and merge it on Monday 🎈

Thanks to everyone who helped and took part in the preparation of this release ❤️
