### ISSUE TITLE
Release v3.1.0

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#381]
What should be included in the new release v3.1.0.

**Improvements:**
- [x] Don't lint backup files (https://github.com/dotenv-linter/dotenv-linter/issues/367)
- [x] Check variable usage before checking sort order
   - [x] Add method to get substitution key to LineEntry (https://github.com/dotenv-linter/dotenv-linter/issues/379)
   - [x] Allow unordered keys for substituion variables (https://github.com/dotenv-linter/dotenv-linter/issues/382)
   - [x] Don't fix key order for substitution variables (https://github.com/dotenv-linter/dotenv-linter/issues/383)
- [x] Add a benchmark for the `check` function (https://github.com/dotenv-linter/dotenv-linter/pull/376)
- [x] Add a benchmark for the `fix` function (#389)
- [x] Add a benchmark for the `compare` function (#390)
- [x] Print a message "Nothing to check" (#384)
- [x] Print a message "Nothing to fix"  (#385)
- [x] Print a message "Nothing to compare"  (#386)
- [x] Use [Rc](https://doc.rust-lang.org/std/rc/index.html) for `LineEntry` to reduce memory consumption (#388)
- [x] Replace `String` on `Into<String>` for all `TestDir` methods (#387)
- [x] Get rid of `String::from` when creating `LineEntry` (#403)
- [x] Add check: Substitution keys (#407)
- [x] Add fixer: Substitution keys (#428)
- [x] Fix `QuoteCharacterChecker` for values with substitution keys (#408)
- [x] Fix the possibility of incorrectly fixing of the ENV file (#409)
- [x] Refactor hard-coded mandatory Fixers (#411)
---

**Infrastructure:**
- [x] Use [clippy-check](https://github.com/actions-rs/clippy-check) to run clippy (https://github.com/dotenv-linter/dotenv-linter/pull/375)
- [x] Add a GitHub Action to compare benchmarks (https://github.com/dotenv-linter/dotenv-linter/pull/378)
- [x] Add action-hadolint (#380)

---

**GitHub Action:**
- [x] Migrate from docker to composite run actions (https://github.com/dotenv-linter/action-dotenv-linter/pull/28) 
- [x] Implement code suggestions (https://github.com/dotenv-linter/action-dotenv-linter/pull/29)
---

What do you think should be included in the new release?
/cc @dotenv-linter/core
